# Generated by Django 4.2.4 on 2023-09-22 06:07

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=50)),
                ('public_date', models.DateField(default=django.utils.timezone.now, null=True)),
                ('end_date', models.DateField(default=datetime.datetime(2023, 9, 23, 6, 7, 32, 592066, tzinfo=datetime.timezone.utc), null=True)),
            ],
        ),
        migrations.CreateModel(
            name='choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=25)),
                ('questions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.questions')),
            ],
        ),
    ]
