# Generated by Django 4.2.4 on 2023-09-22 11:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2023, 9, 23, 11, 18, 31, 836286, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
