# Generated by Django 4.2.4 on 2023-09-22 13:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_alter_questions_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='votes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='questions',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2023, 9, 23, 13, 48, 47, 146271, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
